### ISSUE TITLE
Z's Algorithm

### ISSUE THREAD

**Issue by akarshan2602** [giyasht/Algorithms#24]
Can I add Z's Algorithm? @giyasht

**Comment by giyasht** [comment]
Sure, you can add any algorithm

**Comment by akarshan2602** [comment]
Yeh thanks!

**Comment by drishyadamodaran** [comment]
@giyasht pls review my PR

**Comment by giyasht** [comment]
> @giyasht pls review my PR

sure

**Comment by akarshan2602** [comment]
wait? is this issue closed??
